---
- hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks:

     - name: Install Java on Host Machines
       action: yum pkg=java-17-amazon-corretto state=present

     - name: Install Python on Host Machines
       action: yum pkg=python3 state=present

     - name: Install webservers on Host Machines
       action: yum pkg=httpd state=present

     - name: start webservers on Host Machines
       action: yum pkg=httpd state=started

     - name: Stop webservers server on Host Machines
       action: service name=httpd state=stopped

     - name: Restarted webservers on Host Machines
       action: yum pkg=httpd state=restarted

     - name: Install MySQL on Host Machines
       action: yum pkg=mariadb105 state=present